package gotask

import "time"

// DefaultQueue is the default queue name used when no queue is specified in JobOpts
const DefaultQueue = "gotask:tasks"

// defaultMaxRetry is the default maximum retry count
const defaultMaxRetry uint32 = 1

// Status constants define the lifecycle states of a job
const (
	// StatusStarted is the initial state when a job is pushed onto the broker.
	// This is set immediately when Enqueue() is called.
	StatusStarted = "queued"

	// StatusProcessing is set when a worker picks up the job and starts executing it.
	StatusProcessing = "processing"

	// StatusFailed is set when a job completes with an error after all retries are exhausted.
	StatusFailed = "failed"

	// StatusDone is set when a job completes successfully without errors.
	StatusDone = "successful"

	// StatusRetrying is set when a job fails but will be retried.
	// This is a temporary state before re-enqueuing.
	StatusRetrying = "retrying"
)

type Job struct {
	// Task is the name of the registered handler/processor.
	// This must match a name registered via RegisterProcessor().
	Task string

	// Payload is the arbitrary byte data passed to the handler.
	// The handler is responsible for unmarshaling this
	Payload []byte

	// Opts contains configuration options for this job.
	Opts JobOpts

	// OnSuccess contains jobs that should be enqueued if this job succeeds.
	OnSuccess []*Job

	// OnError contains jobs that should be enqueued if this job fails.
	OnError []*Job
}

type JobOpts struct {
	// ID is an optional unique identifier for the job.
	// If empty, DefaultMeta() will generate a UUID.
	// This allows clients to track jobs by a known ID.
	Id string

	// Queue is the name of the queue where this job will be enqueued.
	// If empty, DefaultQueue is used.
	Queue string

	// ETA is when the job should be executed.
	// If zero, the job is enqueued immediately.
	ETA time.Time

	// MaxRetries is the maximum number of times to retry the job if it fails.
	MaxRetries uint32

	// Schedule is a cron expression for recurring jobs.
	Schedule string

	// Timeout is the maximum duration the job handler can run.
	Timeout time.Duration
}

type Meta struct {
	// ID is the unique identifier for this job instance.
	// This is set from JobOpts.ID or generated by DefaultMeta().
	Id string

	// OnSuccessIDs stores the IDs of jobs enqueued after this job succeeds.
	OnSuccessIds []string

	// Status is the current lifecycle state
	Status string

	// Queue is the queue name where this job is/was enqueued.
	Queue string

	// Schedule is the cron expression if this is a recurring job.
	Schedule string

	// MaxRetry is the maximum retry count
	MaxRetry uint32

	// Retried is the current number of retries attempted.
	Retried uint32

	// PrevErr stores the error message from the last failed attempt.
	PrevErr string

	// ProcessedAt is the timestamp when the job status was last updated.
	ProcessedAt time.Time

	// PrevJobResult contains the result bytes from the previous job in a chain.
	PrevJobResult []byte
}
